import { NextResponse } from 'next/server';
import { ProjectBlueprint } from '@/lib/types';
import { log } from '@/lib/logger';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const blueprint: ProjectBlueprint = body.blueprint;
    const clientToken = body.githubToken;
    const token = clientToken || process.env.GITHUB_TOKEN;

    if (!token) {
      return NextResponse.json(
        {
          success: false,
          error: 'GitHub Token required',
          notice: 'Please add your GITHUB_TOKEN in .env.local or API Keys settings to create real repositories.',
        },
        { status: 400 }
      );
    }

    if (!blueprint || !blueprint.title) {
      return NextResponse.json({ success: false, error: 'Blueprint data is required' }, { status: 400 });
    }

    // Sanitize repo name
    const sanitizedName = (blueprint.title || 'idea-forge-project')
      .toLowerCase()
      .replace(/[^a-z0-9-_]/g, '-')
      .replace(/-+/g, '-')
      .slice(0, 50);

    const repoName = `${sanitizedName}-${Date.now().toString().slice(-4)}`;
    log.info(`[GitHub Create Repo] Provisioning repository "${repoName}"...`);
    log.info(`[GitHub Create Repo] GITHUB_TOKEN defined: ${!!token} | source: ${token ? (token.startsWith('ghp_') ? 'PAT (ghp_)' : 'other format') : 'MISSING'}`);

    const headers = {
      'Accept': 'application/vnd.github.v3+json',
      'Authorization': `token ${token}`,
      'User-Agent': 'IdeaForge-Copilot',
      'Content-Type': 'application/json',
    };

    log.info(`[GitHub Create Repo] Authorization header prefix sent: ${headers['Authorization'].slice(0, 10)}`);

    // 1. Create Repository via GitHub API
    const createRepoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,

      body: JSON.stringify({
        name: repoName,
        description: blueprint.tagline || `Generated by IdeaForge AI Copilot: ${blueprint.problemStatement.slice(0, 100)}`,
        private: false,
        auto_init: false,
      }),
    });

    const repoData = await createRepoRes.json();
    log.info(`[GitHub Create Repo] Response status: ${createRepoRes.status} | X-RateLimit-Limit: ${createRepoRes.headers.get('X-RateLimit-Limit')} | X-RateLimit-Remaining: ${createRepoRes.headers.get('X-RateLimit-Remaining')} | X-OAuth-Scopes: ${createRepoRes.headers.get('X-OAuth-Scopes') || '(none)'}`);

    if (!createRepoRes.ok) {
      log.error(`[GitHub Create Repo] API Error ${createRepoRes.status}:`, repoData);
      return NextResponse.json(
        {
          success: false,
          error: repoData.message || 'Failed to create repository on GitHub',
          details: repoData,
        },
        { status: createRepoRes.status }
      );
    }

    const owner = repoData.owner?.login || 'user';
    const htmlUrl = repoData.html_url || `https://github.com/${owner}/${repoName}`;
    log.info(`[GitHub Create Repo] Created repo: ${htmlUrl}`);

    // Helper to put file content
    const createFile = async (filePath: string, content: string, message: string) => {
      try {
        const fileUrl = `https://api.github.com/repos/${owner}/${repoName}/contents/${filePath}`;
        const base64Content = Buffer.from(content).toString('base64');
        await fetch(fileUrl, {
          method: 'PUT',
          headers,
          body: JSON.stringify({
            message,
            content: base64Content,
          }),
        });
      } catch (err) {
        log.warn(`[GitHub Create Repo] File upload notice for ${filePath}:`, err);
      }
    };

    // 2. Generate README.md content
    const apisSection = blueprint.apisAndDatasets && blueprint.apisAndDatasets.length > 0
      ? `\n\n---\n\n## 🔌 Recommended APIs & Datasets\n${blueprint.apisAndDatasets.map((a) => `- **${a.name}** (${a.type}): ${a.description}\n  - *Use Case*: ${a.useCase}\n  - *Access*: [${a.accessUrl}](${a.accessUrl}) (${a.licenseOrTier})`).join('\n')}`
      : '';

    const timelineSection = blueprint.timeline
      ? `\n\n---\n\n## ⏱️ Development Roadmap & Timeline\n- **Total Build Estimate**: ${blueprint.timeline.totalEstimatedHours} Hours (${blueprint.timeline.totalEstimatedWeeks} Weeks)\n- **Critical Path**: ${blueprint.timeline.criticalPath}\n${blueprint.timeline.phases.map((p) => `- **${p.phaseName}** (${p.duration}): ${p.goal}`).join('\n')}`
      : '';

    const readmeContent = `# ${blueprint.title}

> ${blueprint.tagline}

## 🎯 Executive Summary
${blueprint.executiveSummary}

## 🚨 Problem Statement
${blueprint.problemStatement}

## 💡 Unique Value Proposition
${blueprint.uniqueValueProposition}

---

## 🏗️ System Architecture
${blueprint.architectureNodes.map((n, i) => `### Node 0${i + 1}: ${n.title} (${n.tech})\n- **Category**: ${n.category}\n- **Description**: ${n.description}`).join('\n\n')}

---

## ⚙️ Tech Stack
${blueprint.techStack.map((t) => `- **${t.category}**: ${t.chosen}\n  - *Rationale*: ${t.rationale}\n  - *Alternatives*: ${t.alternatives.join(', ')}`).join('\n')}${apisSection}${timelineSection}

---

## 📅 Milestones Roadmap & Actionable Tasks
${blueprint.milestones.map((m) => `### Sprint ${m.week}: ${m.title} (${m.duration})\n${m.actionableSteps ? m.actionableSteps.map(s => `- [ ] ${s}`).join('\n') + '\n' : ''}- **Deliverables**: ${m.deliverables.join(', ')}\n- **Risk**: ${m.potentialRisk}`).join('\n\n')}

---

*Generated by [IdeaForge AI Research & Innovation Copilot](https://github.com)*
`;

    // 3. Generate package.json
    const packageJsonContent = JSON.stringify(
      {
        name: repoName,
        version: '0.1.0',
        private: true,
        scripts: {
          dev: 'next dev',
          build: 'next build',
          start: 'next start',
        },
        dependencies: {
          next: '^14.2.0',
          react: '^18.3.0',
          'react-dom': '^18.3.0',
          'lucide-react': '^0.350.0',
          'framer-motion': '^11.0.0',
          clsx: '^2.1.0',
          'tailwind-merge': '^2.2.0',
        },
        devDependencies: {
          typescript: '^5.4.0',
          tailwindcss: '^3.4.0',
          '@types/react': '^18.2.0',
        },
      },
      null,
      2
    );

    // Populate repository files
    await createFile('README.md', readmeContent, 'docs: add auto-generated IdeaForge blueprint specification');
    await createFile('package.json', packageJsonContent, 'chore: add project dependencies package.json');
    
    if (blueprint.scaffoldFiles && blueprint.scaffoldFiles.length > 0) {
      for (const file of blueprint.scaffoldFiles) {
        if (file.filePath !== 'README.md') {
          await createFile(file.filePath, file.content, `feat: add ${file.filePath} scaffold`);
        }
      }
    }

    return NextResponse.json({
      success: true,
      repoName,
      repoUrl: htmlUrl,
      owner,
    });
  } catch (err: any) {
    log.error('[GitHub Create Repo] Exception:', err);
    return NextResponse.json(
      { success: false, error: err.message || 'Internal server error' },
      { status: 500 }
    );
  }
}
